name: Deploy Dist
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
        # run: |
        #   echo "cloning repo..."
        #   echo "${{ toJson(github) }}"
        #   git clone https://github.com/${{ github.repository }}.git
        # shell: bash
      - name: Install Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: print node version
        run: node -v
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test  